export enum ENVEnum {
  NODE_ENV = 'NODE_ENV',
  DATABASE_URL = 'DATABASE_URL',

  PORT = 'PORT',
  BASE_URL = 'BASE_URL',

  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',

  MAIL_USER = 'MAIL_USER',
  MAIL_PASS = 'MAIL_PASS',

  SUPER_ADMIN_EMAIL = 'SUPER_ADMIN_EMAIL',
  SUPER_ADMIN_PASS = 'SUPER_ADMIN_PASS',
  SUPER_ADMIN_PHONE = 'SUPER_ADMIN_PHONE',
  SUPER_ADMIN_EMPLOYEE_ID = 'SUPER_ADMIN_EMPLOYEE_ID',

  ADMIN_EMAIL = 'ADMIN_EMAIL',
  ADMIN_PASS = 'ADMIN_PASS',
  ADMIN_PHONE = 'ADMIN_PHONE',
  ADMIN_EMPLOYEE_ID = 'ADMIN_EMPLOYEE_ID',

  REDIS_URL = 'REDIS_URL',
  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',

  CLOUDINARY_CLOUD_NAME = 'CLOUDINARY_CLOUD_NAME',
  CLOUDINARY_API_KEY = 'CLOUDINARY_API_KEY',
  CLOUDINARY_API_SECRET = 'CLOUDINARY_API_SECRET',

  FIREBASE_PROJECT_ID = 'FIREBASE_PROJECT_ID',
  FIREBASE_CLIENT_EMAIL = 'FIREBASE_CLIENT_EMAIL',
  FIREBASE_PRIVATE_KEY = 'FIREBASE_PRIVATE_KEY',
}
