services:
  server:
    container_name: jesus-server-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@db:5432/javier_db
      
      JWT_SECRET: asdfkamskfmasklfmaksmfaskfmaksfaopsfmpaomsfpaf
      JWT_EXPIRES_IN: 90d
      
      BASE_URL: https://api.lgcglobalcontractingltd.com/js
      PORT: 5003
      
      MAIL_USER: arafatmannan2019@gmail.com
      MAIL_PASS: eurp zvyi gnoy enag
      
      ADMIN_EMAIL: 'arafatmannan9@gmail.com'
      ADMIN_PASS: 'admin1234'
      ADMIN_PHONE: 9999999999991
      ADMIN_EMPLOYEE_ID: 100001
      
      REDIS_URL: redis://redis:6388
      REDIS_HOST: redis
      REDIS_PORT: 6388

      CLOUDINARY_CLOUD_NAME: dajbvml9v
      CLOUDINARY_API_KEY: 446326388615888
      CLOUDINARY_API_SECRET: h-2JuLgUmuCN-crXiY-JKdcPyxE
    ports:
      - 5003:5003
    depends_on:
      - db
      - redis
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npm run start:prod
      "

  db:
    image: postgres:16
    container_name: javier_db
    restart: always
    # user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: javier_db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5400:5432"

  redis:
    image: redis
    container_name: javier
    restart: always
    ports:
      - '6388:6388'

volumes:
  db-data: